<a href="https://colab.research.google.com/github/cicbeast/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/Raul_LS_DS_Unit_4_Sprint_Challenge_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Chocolate Gummy Bears](#Q2)
    - Perceptron
    - Multilayer Perceptron
4. [Keras MMP](#Q3)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:** The base unit of Neural networks. It is made up of input hidden and output layers
- **Input Layer:** This contains the initial data that will be passed through the neuron
- **Hidden Layer:** This contains the biases and weights and all the computations that will be done the the data in the input layer
- **Output Layer:** This contains the result of all the previous layers
- **Activation:** This is the normalization of the Neuron's output
- **Backpropagation:** This is the process (algorithm) by which the weights in a neural network are updated through the analysis of each node's loss


## 2. Chocolate Gummy Bears <a id="Q2"></a>

Right now, you're probably thinking, "yuck, who the hell would eat that?". Great question. Your candy company wants to know too. And you thought I was kidding about the [Chocolate Gummy Bears](https://nuts.com/chocolatessweets/gummies/gummy-bears/milk-gummy-bears.html?utm_source=google&utm_medium=cpc&adpos=1o1&gclid=Cj0KCQjwrfvsBRD7ARIsAKuDvMOZrysDku3jGuWaDqf9TrV3x5JLXt1eqnVhN0KM6fMcbA1nod3h8AwaAvWwEALw_wcB). 

Let's assume that a candy company has gone out and collected information on the types of Halloween candy kids ate. Our candy company wants to predict the eating behavior of witches, warlocks, and ghosts -- aka costumed kids. They shared a sample dataset with us. Each row represents a piece of candy that a costumed child was presented with during "trick" or "treat". We know if the candy was `chocolate` (or not chocolate) or `gummy` (or not gummy). Your goal is to predict if the costumed kid `ate` the piece of candy. 

If both chocolate and gummy equal one, you've got a chocolate gummy bear on your hands!?!?!
![Chocolate Gummy Bear](https://ed910ae2d60f0d25bcb8-80550f96b5feb12604f4f720bfefb46d.ssl.cf1.rackcdn.com/3fb630c04435b7b5-2leZuM7_-zoom.jpg)

In [2]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

candy = pd.read_csv('chocolate_gummy_bears.csv')

Saving chocolate_gummy_bears.csv to chocolate_gummy_bears (2).csv


In [22]:
candy.head(20)

chocolate  gummy  ate
0           0      1    1
1           1      0    1
2           0      1    1
3           0      0    0
4           1      1    0
5           0      1    1
6           0      0    0
7           1      1    0
8           0      0    0
9           0      0    0
10          0      1    1
11          1      1    0
12          0      0    0
13          0      1    1
14          0      1    1
15          1      0    0
16          1      0    1
17          0      1    1
18          1      1    0
19          0      1    1

### Perceptron

To make predictions on the `candy` dataframe. Build and train a Perceptron using numpy. Your target column is `ate` and your features: `chocolate` and `gummy`. Do not do any feature engineering. :P

Once you've trained your model, report your accuracy. You will not be able to achieve more than ~50% with the simple perceptron. Explain why you could not achieve a higher accuracy with the *simple perceptron* architecture, because it's possible to achieve ~95% accuracy on this dataset. Provide your answer in markdown (and *optional* data anlysis code) after your perceptron implementation. 

In [0]:
# Start your candy perceptron here
import numpy as np
from sklearn.metrics import accuracy_score


# We need the inputs and correct outputs from the dataframe
X = candy[['chocolate', 'gummy']].values
y = candy['ate'].values

# Seed our Randomizer
np.random.seed(42) #Goodbye and Thanks for all the fish

# Define our activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# And its derivative
def sigmoid_deriv(x):
    sx = sigmoid(x)
    return sx * (1 -sx)

# initiate our weights
weights = 2 * np.random.random((2, 1)) -1

In [25]:
# And now the for loop for our Perceptron
for iteration in range(5):
    # We get the weighted sum
    weighted_sum = np.dot(X, weights)
    
    # Then we run the weighted sums through the activation function
    activated_outputs = sigmoid(weighted_sum)
    # Calculate our errors
    error = y - activated_outputs
    # and the adjustments based on those errors
    adjustments = error * sigmoid_deriv(activated_outputs)
    # And finally we adjust the weights
    weights = weights + np.dot(X.T, adjustments)

ypred = np.rint(activated_outputs[-1])

Acc = accuracy_score(y, ypred)
print('Accuracy:', Acc)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: RuntimeWarning: overflow encountered in exp
  


Accuracy: 1.0


Sooooooo.... I don't know what went wrong/right here^

Gonna just keep working

### Multilayer Perceptron <a id="Q3"></a>

Using the sample candy dataset, implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your Multilayer Perceptron should be implemented in Numpy. 
Your network must have one hidden layer.

Once you've trained your model, report your accuracy. Explain why your MLP's performance is considerably better than your simple perceptron's on the candy dataset. 

In [0]:
X = candy[['chocolate', 'gummy']].values
y = candy['ate'].values

# Seed our Randomizer
np.random.seed(42) #Goodbye and Thanks for all the fish

class Perceptron:
    def __init__(self): #For reproducability I would put variables here usually 
        # Set up Architecture of Neural Network
        self.inputs = 2
        self.hiddenNodes = 3
        self.outputNodes = 1

        # Initial Weights
        # 2x3 Matrix Array for the First Layer
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
       
        # 3x1 Matrix Array for Hidden to Output
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
    
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoidPrime(self, x):
        sx = self.sigmoid(x)
        return sx * (1 - sx)

    def feed_fwd(self, X):
        # Combining X and weights in a weighted sum
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activation of hidden layer weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden layer and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Activation of output layer weighted sum
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def bkwd(self,X,y,o):
        # Calculate the error (diff between y true and y predicted)
        self.o_error = y - o
        
        # Apply Derivative of Sigmoid to error
        # Which direction do we want to go?
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        # Apply the adjustment (o_delta) to the transformed weights2
        self.z2_error = self.o_delta.dot(self.weights2.T)
        
        # Apply Derivative of Sigmoid to z2 error
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        # Apply adjustments to weights1
        self.weights1 += X.T.dot(self.z2_delta)

        # Apply adjustments to weights2
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)

    def train(self,X,y):
        o = self.feed_fwd(X)
        self.bkwd(X,y,o)



In [28]:
pt = Perceptron()

for i in range(5):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 10 == 0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(pt.feed_fwd(X)))
        print("Loss: \n", str(np.mean(np.square(y - pt.feed_fwd(X)))))
    pt.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [1 1 1 ... 1 1 1]
Predicted Output: 
 [[0.64157044]
 [0.65860075]
 [0.64157044]
 ...
 [0.64157044]
 [0.64157044]
 [0.65860075]]
Loss: 
 0.27256498359528253


ValueError: ignored

I don't know why my o.delta increased to 10,000 I had the same type of issue in part 1. I have no idea how to fix this

P.S. Don't try candy gummy bears. They're disgusting. 

## 3. Keras MMP <a id="Q3"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 3 parameters in order to get a 3 on this section.

In [29]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
234   70    1   0       130   322    0  ...      0      2.4      1   3     2       0
110   64    0   0       180   325    0  ...      1      0.0      2   0     2       1
248   54    1   1       192   283    0  ...      0      0.0      2   1     3       0
9     57    1   2       150   168    0  ...      0      1.6      2   0     2       1
93    54    0   1       132   288    1  ...      1      0.0      2   1     2       1

[5 rows x 14 columns]

In [0]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, train_size=0.75, test_size=0.25, random_state=42)

Xtrain = train.values[:,0:13]
ytrain = train.values[:,-1]
Xtest = test.values[:,0:13]
ytest = test.values[:,-1]

scaler = StandardScaler()

Xtrain = scaler.fit_transform(Xtrain)
Xtest = scaler.transform(Xtest)

In [47]:
print(Xtrain.shape)
Xtrain[:5]

(227, 13)


array([[ 0.38583042,  0.6815542 , -0.95273751, -1.93705804, -0.2556432 ,
        -0.4197211 ,  0.88201044,  0.23464627, -0.6746319 , -0.80164627,
         0.98135127,  0.24087326,  1.05905737],
       [ 0.8292912 ,  0.6815542 ,  1.03140391, -0.09340112, -0.31129953,
        -0.4197211 ,  0.88201044, -0.22138715, -0.6746319 ,  0.66449258,
        -0.60983972,  2.15940768,  1.05905737],
       [-0.16849556,  0.6815542 , -0.95273751,  0.64406165, -0.40406009,
        -0.4197211 , -1.02481213, -1.81750414,  1.48228982, -0.88788974,
         0.98135127, -0.71839395,  1.05905737],
       [ 1.82707795, -1.46723474, -0.95273751, -1.19959527, -1.83257269,
        -0.4197211 ,  0.88201044, -1.17905735, -0.6746319 ,  0.49200565,
        -0.60983972, -0.71839395, -0.55440587],
       [-1.4988779 , -1.46723474,  0.0393332 , -0.09340112, -0.81220655,
        -0.4197211 , -1.02481213,  0.96429976, -0.6746319 ,  0.31951873,
         0.98135127, -0.71839395, -0.55440587]])

In [48]:
print (ytrain.shape)
ytrain[:5]

(227,)


array([0., 1., 1., 1., 1.])

In [0]:
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier


# fix random seed for reproducibility
np.random.seed(812)


In [54]:
def create_model():
    # create model
    model = Sequential()
    model.add(Dense(3, input_dim=13, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

model = KerasClassifier(build_fn=create_model, verbose=0)

param_grid = {'batch_size': [10, 15, 20],
              'epochs': [15, 20, 25]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(Xtrain,ytrain)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Best: 0.7709251098695831 using {'batch_size': 10, 'epochs': 25}
Means: 0.7268722393439204, Stdev: 0.07550562834335717 with: {'batch_size': 10, 'epochs': 15}
Means: 0.599118933015983, Stdev: 0.04181148061698858 with: {'batch_size': 10, 'epochs': 20}
Means: 0.7709251098695831, Stdev: 0.03675747181228809 with: {'batch_size': 10, 'epochs': 25}
Means: 0.6387665171980332, Stdev: 0.13927503555529927 with: {'batch_size': 15, 'epochs': 15}
Means: 0.6167400959829927, Stdev: 0.019977745055631872 with: {'batch_size': 15, 'epochs': 20}
Means: 0.7577092613417672, Stdev: 0.04744698660891673 with: {'batch_size': 15, 'epochs': 25}
Means: 0.5110132056185852, Stdev: 0.057339180345309555 with: {'batch_size': 20, 'epochs': 15}
Means: 0.5550660758816723, Stdev: 0.08944420757083467 with: {'batch_size': 20, 'epochs': 20}
Means: 0.7268722372433163, Stdev: 0.03641363861529828 with: {'batch_size': 20, 'epochs': 25}


In [65]:
def create_model(optimizer='Adam'):
    # create model
    model = Sequential()
    model.add(Dense(3, input_dim=13, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

model = KerasClassifier(build_fn=create_model, epochs=25, batch_size=10, verbose=0)

optimizer = ['Adam', 'Adamax', 'Nadam']
param_grid = dict(optimizer=optimizer)

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(Xtrain,ytrain)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Best: 0.7841409731016286 using {'optimizer': 'Nadam'}
Means: 0.7444933820926145, Stdev: 0.06755828277639891 with: {'optimizer': 'Adam'}
Means: 0.533039637861798, Stdev: 0.032912034944515556 with: {'optimizer': 'Adamax'}
Means: 0.7841409731016286, Stdev: 0.016247663396170797 with: {'optimizer': 'Nadam'}


Best Paramaters:<br> 
Optimization algorithm - Nadam <br>
Epochs - 25<br>
Batch Size - 10